---
version: '2'
services:

  #---------------------------------------------------------------------------#
  # Zookeeper Cluster                                                         #
  # *NB Zookeeper clust should prob go on separate network                    #
  #---------------------------------------------------------------------------#
  zookeeper-1:
    image: confluentinc/cp-zookeeper:3.1.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888
    network_mode: host

  #---------------------------------------------------------------------------#
  # Kafka Cluster                                                             #
  #---------------------------------------------------------------------------#
  kafka-1:
    image: confluentinc/cp-kafka:3.1.0
    network_mode: host
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry-1:
    image: confluentinc/cp-schema-registry:3.1.0
    network_mode: host
    depends_on:
      - "zookeeper-1"
    restart: always
    ports:
      - "8081:8081"
    environment:
      #SR_KAFKASTORE_CONNECTION_URL: "zookeeper-sasl-1:2181"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "localhost:2181"
      SCHEMA_REGISTRY_HOST_NAME: "localhost"
      SCHEMA_REGISTRY_LISTENERS: "http://localhost:8081"

  #---------------------------------------------------------------------------#
  # REST proxy                                                                #
  #---------------------------------------------------------------------------#
  rest-proxy-1:
    image: confluentinc/cp-kafka-rest:3.1.0
    network_mode: host
    depends_on:
      - "kafka-1"
      - "schema-registry-1"
    ports:
      - "8082:8082"
    environment:
      #RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      #RP_ZOOKEEPER_CONNECT: "zookeeper-sasl-1:2181"
      KAFKA_REST_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_REST_LISTENERS: "http://localhost:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://localhost:8081"
      KAFKA_REST_HOST_NAME: "localhost"

  #---------------------------------------------------------------------------#
  # Mongo DB                                                                  #
  #---------------------------------------------------------------------------#
  mongo:
    image: mongo:3.3
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest --noauth
